"""SQLite helpers for metadata generated by the M2 embedding pipeline."""

from __future__ import annotations

import sqlite3
from pathlib import Path
from typing import Iterable, Mapping

import pandas as pd


TRACK_COLUMNS = [
    "faiss_id",
    "track_id",
    "title",
    "display_title",
    "artist_id",
    "artist",
    "album_id",
    "album",
    "duration",
    "primary_tag",
    "tags",
    "audio_url",
    "preview_path",
    "split",
    "pca_1",
    "pca_2",
    "pca_3",
    "pca10_1",
    "pca10_2",
    "pca10_3",
    "pca10_4",
    "pca10_5",
    "pca10_6",
    "pca10_7",
    "pca10_8",
    "pca10_9",
    "pca10_10",
    "umap_1",
    "umap_2",
    "umap_3",
    "cluster",
]


def connect(db_path: Path | str) -> sqlite3.Connection:
    conn = sqlite3.connect(str(db_path))
    conn.row_factory = sqlite3.Row
    return conn


def initialize_schema(conn: sqlite3.Connection) -> None:
    conn.executescript(
        """
        CREATE TABLE IF NOT EXISTS tracks (
            faiss_id INTEGER PRIMARY KEY,
            track_id TEXT UNIQUE,
            title TEXT,
            display_title TEXT,
            artist_id TEXT,
            artist TEXT,
            album_id TEXT,
            album TEXT,
            duration REAL,
            primary_tag TEXT NOT NULL,
            tags TEXT,
            audio_url TEXT,
            preview_path TEXT,
            split TEXT DEFAULT 'eval',
            pca_1 REAL,
            pca_2 REAL,
            pca_3 REAL,
            pca10_1 REAL,
            pca10_2 REAL,
            pca10_3 REAL,
            pca10_4 REAL,
            pca10_5 REAL,
            pca10_6 REAL,
            pca10_7 REAL,
            pca10_8 REAL,
            pca10_9 REAL,
            pca10_10 REAL,
            umap_1 REAL,
            umap_2 REAL,
            umap_3 REAL,
            cluster INTEGER
        );

        CREATE TABLE IF NOT EXISTS evaluations (
            metric TEXT PRIMARY KEY,
            value REAL,
            details_json TEXT
        );

        CREATE TABLE IF NOT EXISTS artists (
            artist_id TEXT PRIMARY KEY,
            display_name TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS albums (
            album_id TEXT PRIMARY KEY,
            artist_id TEXT,
            display_title TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS generated_playlists (
            playlist_id TEXT PRIMARY KEY,
            anchor_faiss_id INTEGER,
            strategy TEXT NOT NULL,
            size INTEGER NOT NULL,
            seed INTEGER,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS playlist_tracks (
            playlist_id TEXT NOT NULL,
            faiss_id INTEGER NOT NULL,
            position INTEGER NOT NULL,
            role TEXT DEFAULT 'member',
            PRIMARY KEY (playlist_id, faiss_id)
        );
        """
    )
    conn.commit()


def insert_track(conn: sqlite3.Connection, row: Mapping[str, object]) -> None:
    values = {column: row.get(column) for column in TRACK_COLUMNS}
    placeholders = ", ".join(":" + column for column in TRACK_COLUMNS)
    columns = ", ".join(TRACK_COLUMNS)
    conn.execute(
        f"INSERT OR REPLACE INTO tracks ({columns}) VALUES ({placeholders})",
        values,
    )


def insert_tracks(conn: sqlite3.Connection, rows: Iterable[Mapping[str, object]]) -> None:
    for row in rows:
        insert_track(conn, row)
    conn.commit()


def load_tracks(db_path: Path | str) -> pd.DataFrame:
    with connect(db_path) as conn:
        tables = {
            row["name"]
            for row in conn.execute(
                "SELECT name FROM sqlite_master WHERE type = 'table'"
            ).fetchall()
        }
        if {"artists", "albums"}.issubset(tables):
            return pd.read_sql_query(
                """
                SELECT
                    t.*,
                    COALESCE(t.display_title, t.title, 'Jamendo Track ' || t.track_id) AS track_display_title,
                    COALESCE(a.display_name, t.artist, 'Unknown Artist') AS artist_display_name,
                    COALESCE(al.display_title, t.album, 'Unknown Album') AS album_display_title
                FROM tracks t
                LEFT JOIN artists a ON a.artist_id = COALESCE(t.artist_id, t.artist)
                LEFT JOIN albums al ON al.album_id = COALESCE(t.album_id, t.album)
                ORDER BY t.faiss_id ASC
                """,
                conn,
            )
        return pd.read_sql_query("SELECT * FROM tracks ORDER BY faiss_id ASC", conn)


def update_projection_columns(
    db_path: Path | str,
    frame: pd.DataFrame,
    columns: Iterable[str],
) -> None:
    column_list = list(columns)
    with connect(db_path) as conn:
        for _, row in frame.iterrows():
            assignments = ", ".join(f"{column} = ?" for column in column_list)
            values = [row.get(column) for column in column_list]
            values.append(int(row["faiss_id"]))
            conn.execute(
                f"UPDATE tracks SET {assignments} WHERE faiss_id = ?",
                values,
            )
        conn.commit()


def upsert_evaluation(conn: sqlite3.Connection, metric: str, value: float | None, details_json: str) -> None:
    conn.execute(
        """
        INSERT OR REPLACE INTO evaluations (metric, value, details_json)
        VALUES (?, ?, ?)
        """,
        (metric, value, details_json),
    )
