"""SQLite helpers for metadata generated by the M2 embedding pipeline."""

from __future__ import annotations

import sqlite3
from pathlib import Path
from typing import Iterable, Mapping

import pandas as pd


TRACK_COLUMNS = [
    "faiss_id",
    "track_id",
    "title",
    "artist",
    "album",
    "duration",
    "primary_tag",
    "tags",
    "audio_url",
    "preview_path",
    "split",
    "pca_1",
    "pca_2",
    "pca_3",
    "pca10_1",
    "pca10_2",
    "pca10_3",
    "pca10_4",
    "pca10_5",
    "pca10_6",
    "pca10_7",
    "pca10_8",
    "pca10_9",
    "pca10_10",
    "umap_1",
    "umap_2",
    "umap_3",
    "cluster",
]


def connect(db_path: Path | str) -> sqlite3.Connection:
    conn = sqlite3.connect(str(db_path))
    conn.row_factory = sqlite3.Row
    return conn


def initialize_schema(conn: sqlite3.Connection) -> None:
    conn.executescript(
        """
        CREATE TABLE IF NOT EXISTS tracks (
            faiss_id INTEGER PRIMARY KEY,
            track_id TEXT UNIQUE,
            title TEXT,
            artist TEXT,
            album TEXT,
            duration REAL,
            primary_tag TEXT NOT NULL,
            tags TEXT,
            audio_url TEXT,
            preview_path TEXT,
            split TEXT DEFAULT 'eval',
            pca_1 REAL,
            pca_2 REAL,
            pca_3 REAL,
            pca10_1 REAL,
            pca10_2 REAL,
            pca10_3 REAL,
            pca10_4 REAL,
            pca10_5 REAL,
            pca10_6 REAL,
            pca10_7 REAL,
            pca10_8 REAL,
            pca10_9 REAL,
            pca10_10 REAL,
            umap_1 REAL,
            umap_2 REAL,
            umap_3 REAL,
            cluster INTEGER
        );

        CREATE TABLE IF NOT EXISTS evaluations (
            metric TEXT PRIMARY KEY,
            value REAL,
            details_json TEXT
        );
        """
    )
    conn.commit()


def insert_track(conn: sqlite3.Connection, row: Mapping[str, object]) -> None:
    values = {column: row.get(column) for column in TRACK_COLUMNS}
    placeholders = ", ".join(":" + column for column in TRACK_COLUMNS)
    columns = ", ".join(TRACK_COLUMNS)
    conn.execute(
        f"INSERT OR REPLACE INTO tracks ({columns}) VALUES ({placeholders})",
        values,
    )


def insert_tracks(conn: sqlite3.Connection, rows: Iterable[Mapping[str, object]]) -> None:
    for row in rows:
        insert_track(conn, row)
    conn.commit()


def load_tracks(db_path: Path | str) -> pd.DataFrame:
    with connect(db_path) as conn:
        return pd.read_sql_query(
            "SELECT * FROM tracks ORDER BY faiss_id ASC",
            conn,
        )


def update_projection_columns(
    db_path: Path | str,
    frame: pd.DataFrame,
    columns: Iterable[str],
) -> None:
    column_list = list(columns)
    with connect(db_path) as conn:
        for _, row in frame.iterrows():
            assignments = ", ".join(f"{column} = ?" for column in column_list)
            values = [row.get(column) for column in column_list]
            values.append(int(row["faiss_id"]))
            conn.execute(
                f"UPDATE tracks SET {assignments} WHERE faiss_id = ?",
                values,
            )
        conn.commit()
